import re
#  need to <space>' or '<space>

contraction_patterns = [
    (" you re ", " you're "),
    (" they re ", " they're "),
    (" he s ", " he's "),
    (" she s ", " she's "),
    (" it s ", " it's "),
    (" we re ", " we're "),
    (" that s ", " that's "),
    (" who s ", " who's "),
    (" what s ", " what's "),
    (" where s ", " where's "),
    (" when s ", " when's "),
    (" how s ", " how's "),
    (" let s ", " let's "),
    (" ain t ", " ain't "),
    (" aren t ", " aren't "),
    (" can t ", " can't "),
    (" could ve ", " could've "),
    (" couldn t ", " couldn't "),
    (" didn t ", " didn't "),
    (" doesn t ", " doesn't "),
    (" don t ", " don't "),
    (" hadn t ", " hadn't "),
    (" hasn t ", " hasn't "),
    (" haven t ", " haven't "),
    (" he d ", " he'd "),
    (" he ll ", " he'll "),
    (" he s ", " he's "),
    (" how d ", " how'd "),
    (" how ll ", " how'll "),
    (" how re ", " how're "),
    (" how s ", " how's "),
    (" I d ", " I'd "),
    (" I ll ", " I'll "),
    (" I m ", " I'm "),
    (" I ve ", " I've "),
    (" isn t ", " isn't "),
    (" it d ", " it'd "),
    (" it ll ", " it'll "),
    (" it s ", " it's "),
    (" let s ", " let's "),
    (" ma am ", " ma'am "),
    (" might ve ", " might've "),
    (" must ve ", " must've "),
    (" mustn t ", " mustn't "),
    (" needn t ", " needn't "),
    (" o clock ", " o'clock "),
    (" shan t ", " shan't "),
    (" she d ", " she'd "),
    (" she ll ", " she'll "),
    (" she s ", " she's "),
    (" should ve ", " should've "),
    (" shouldn t ", " shouldn't "),
    (" that d ", " that'd "),
    (" that ll ", " that'll "),
    (" that re ", " that're "),
    (" that s ", " that's "),
    (" there d ", " there'd "),
    (" there ll ", " there'll "),
    (" there re ", " there're "),
    (" there s ", " there's "),
    (" they d ", " they'd "),
    (" they ll ", " they'll "),
    (" they re ", " they're "),
    (" they ve ", " they've "),
    (" wasn t ", " wasn't "),
    (" we d ", " we'd "),
    (" we ll ", " we'll "),
    (" we re ", " we're "),
    (" weren t ", " weren't "),
    (" what ll ", " what'll "),
    (" what re ", " what're "),
    (" what s ", " what's "),
    (" what ve ", " what've "),
    (" when s ", " when's "),
    (" where d ", " where'd "),
    (" where ll ", " where'll "),
    (" where re ", " where're "),
    (" where s ", " where's "),
    (" where ve ", " where've "),
    (" who ll ", " who'll "),
    (" who re ", " who're "),
    (" who s ", " who's "),
    (" who ve ", " who've "),
    (" why d ", " why'd "),
    (" why re ", " why're "),
    (" why s ", " why's "),
    (" will ve ", " will've "),
    (" won t ", " won't "),
    (" would ve ", " would've "),
    (" wouldn t ", " wouldn't "),
    (" y all ", " y'all "),
    (" you d ", " you'd "),
    (" you ll ", " you'll "),
    (" you re ", " you're "),
    (" you ve ", " you've "),
    (" should ve ", " should've "),
    (" could ve ", " could've "),
    (" would ve ", " would've "),
    (" might ve ", " might've "),
    (" must ve ", " must've "),
    (" let us ", " let's "),
    (" youre ", " you're "),
    (" theyre ", " they're "),
    (" hes ", " he's "),
    (" shes ", " she's "),
    (" its ", " it's "),
    (" were ", " we're "),
    (" thats ", " that's "),
    (" whos ", " who's "),
    (" whats ", " what's "),
    (" wheres ", " where's "),
    (" whens ", " when's "),
    (" hows ", " how's "),
    (" lets ", " let's "),
    (" aint ", " ain't "),
    (" arent ", " aren't "),
    (" cant ", " can't "),
    (" couldve ", " could've "),
    (" couldnt ", " couldn't "),
    (" didnt ", " didn't "),
    (" doesnt ", " doesn't "),
    (" dont ", " don't "),
    (" hadnt ", " hadn't "),
    (" hasnt ", " hasn't "),
    (" havent ", " haven't "),
    (" hed ", " he'd "),
    (" hell ", " he'll "),
    (" hes ", " he's "),
    (" howd ", " how'd "),
    (" howll ", " how'll "),
    (" howre ", " how're "),
    (" hows ", " how's "),
    (" Id ", " I'd "),
    (" Ill ", " I'll "),
    (" Im ", " I'm "),
    (" Ive ", " I've "),
    (" isnt ", " isn't "),
    (" itd ", " it'd "),
    (" itll ", " it'll "),
    (" its ", " it's "),
    (" lets ", " let's "),
    (" maam ", " ma'am "),
    (" mightve ", " might've "),
    (" mustve ", " must've "),
    (" mustnt ", " mustn't "),
    (" neednt ", " needn't "),
    (" oclock ", " o'clock "),
    (" shant ", " shan't "),
    (" shed ", " she'd "),
    (" shell ", " she'll "),
    (" shes ", " she's "),
    (" shouldve ", " should've "),
    (" shouldnt ", " shouldn't "),
    (" thatd ", " that'd "),
    (" thatll ", " that'll "),
    (" thatre ", " that're "),
    (" thats ", " that's "),
    (" thered ", " there'd "),
    (" therell ", " there'll "),
    (" therere ", " there're "),
    (" theres ", " there's "),
    (" theyd ", " they'd "),
    (" theyll ", " they'll "),
    (" theyre ", " they're "),
    (" theyve ", " they've "),
    (" wasnt ", " wasn't "),
    (" wed ", " we'd "),
    (" well ", " we'll "),
    (" were ", " we're "),
    (" werent ", " weren't "),
    (" whatll ", " what'll "),
    (" whatre ", " what're "),
    (" whats ", " what's "),
    (" whatve ", " what've "),
    (" whens ", " when's "),
    (" whered ", " where'd "),
    (" wherell ", " where'll "),
    (" wherere ", " where're "),
    (" wheres ", " where's "),
    (" whereve ", " where've "),
    (" wholl ", " who'll "),
    (" whore ", " who're "),
    (" whos ", " who's "),
    (" whove ", " who've "),
    (" whyd ", " why'd "),
    (" whyre ", " why're "),
    (" whys ", " why's "),
    (" willve ", " will've "),
    (" wont ", " won't "),
    (" wouldve ", " would've "),
    (" wouldnt ", " wouldn't "),
    (" yall ", " y'all "),
    (" youd ", " you'd "),
    (" youll ", " you'll "),
    (" youre ", " you're "),
    (" youve ", " you've "),
    (" shouldve ", " should've "),
    (" couldve ", " could've "),
    (" wouldve ", " would've "),
    (" mightve ", " might've "),
    (" mustve ", " must've "),
    (" letus ", " let's ")
]
 
def clean_special_characters(input_string):
    # Replace all special characters (except ')
    cleaned_string = re.sub(r"[^a-zA-Z0-9\s']", ' ', input_string)
    #Handle ' between words
    for pattern, replacement in contraction_patterns:
        cleaned_string = re.sub(pattern, replacement, cleaned_string) 
    # Remove ' if it's before or after a whitespace or is the last character in the sentence
    cleaned_string = re.sub(r"(^|\s)'|'(\s|$)", ' ', cleaned_string)
    # Remove more than one whitespace
    cleaned_string = re.sub(r'\s+', ' ', cleaned_string).strip()
    return cleaned_string

f = open('./data/eng_train.txt', 'r')
lines = f.readlines()
f1 = open('./data/eng_train_clean.txt', 'w')
for line in lines:
    cleaned_text = clean_special_characters(line.lower())
    f1.write(cleaned_text + '\n')
