import csv
import pandas as pd
import re
import numpy as np
import copy
from nltk.translate.bleu_score import sentence_bleu
from nltk import word_tokenize

def clean(input_string):
  li = input_string.split('\n')
  result_list = [item.strip()[3:] for item in li]
#   print(result_list)
#   result_list[9] = result_list[9][1:] #do this for every 10th result
  return result_list

def calculate_bleu(candidate, reference):
    '''
    candidate, reference: generated and ground-truth sentences
    '''
    reference = word_tokenize(reference)
    candidate = word_tokenize(candidate)
    score = sentence_bleu(reference, candidate)
    return score

def get_bleu_score(sentence, remaining_sentences):
    lst = []
    for i in remaining_sentences:
        bleu = sentence_bleu(sentence, i)
        lst.append(bleu)
    return lst

def calculate_selfBleu(sentences):
    '''
    sentences - list of sentences generated by NLG system
    '''
    bleu_scores = []
    for i in sentences:
        sentences_copy = copy.deepcopy(sentences)
        remaining_sentences = sentences_copy.remove(i)
        # print(sentences_copy)
        bleu = get_bleu_score(i,sentences_copy)
        bleu_scores.append(bleu)
    return np.mean(bleu_scores)

df_ip1 = pd.read_csv('./data/palm_generate10.csv')
df_ip2 = pd.read_csv('./data/palm2_generate10.csv')
total_sentences = len(df_ip2)
count = 0
ans1, ans2 = 0, 0
for i in range(0, total_sentences):
    # print(df_ip2.iloc[i]['Output 10 codeswitch palm2'][2:])\
    s1 = df_ip1.iloc[i]['Output 10 codeswitch palm'][2:]
    s2 = df_ip2.iloc[i]['Output 10 codeswitch palm2'][2:]
    # if(i == 3):
    #     print(s1)
    if(s1 != '' and s2 != ''):
        # cs1 += clean(s1)
        # cs2 += clean(s2)
        try:
            ans1 += calculate_selfBleu(clean(s1))
            ans2 += calculate_selfBleu(clean(s2))
            # print(count)
            count += 1
        except:
            print(i)

# ans1 = calculate_selfBleu(cs1)
# ans2 = calculate_selfBleu(cs2)
print("Self Bleu 1: ", ans1)
print("Self Bleu 2: ", ans2)
print("Count", count)